# Ejercicios Nivel Intermedio

In [1]:
# Importando librerias
import numpy as np

1. Manipulación Avanzada:

Crea una matriz de 5x5 con números aleatorios. Encuentra el valor mínimo de cada fila y réstalo a todos los elementos de esa fila.

In [6]:
matriz = np.random.rand(5,5)
print(matriz)
valor_minimo_de_la_matriz = np.min(matriz, axis=1)
print(valor_minimo_de_la_matriz)
matriz_restada_con_su_valor_minimo = matriz - np.expand_dims(valor_minimo_de_la_matriz, axis=1)
print(matriz_restada_con_su_valor_minimo)

[[0.67247042 0.44997749 0.29844026 0.15376262 0.58847302]
 [0.95140167 0.75193241 0.10880472 0.4533013  0.99875064]
 [0.66068388 0.06785106 0.37706928 0.37802188 0.97577585]
 [0.03783373 0.39271613 0.55552499 0.63217165 0.6200492 ]
 [0.7780306  0.23979898 0.3898923  0.45761137 0.04377123]]
[0.15376262 0.10880472 0.06785106 0.03783373 0.04377123]
[[ 0.51870779  0.34117278  0.2305892   0.11592889  0.54470178]
 [ 0.79763904  0.64312769  0.04095366  0.41546757  0.9549794 ]
 [ 0.50692126 -0.04095366  0.30921822  0.34018815  0.93200462]
 [-0.11592889  0.28391141  0.48767394  0.59433792  0.57627796]
 [ 0.62426797  0.13099426  0.32204125  0.41977763  0.        ]]


2. Creación de Tensores:

Crea un tensor tridimensional (3x3x3) con números aleatorios. Calcula la suma de todos los elementos en la dimensión 1.

In [19]:
# Crear un tensor tridimensional (3x3x3) con números aleatorios.
tensor_tridimensional = np.random.randint(0, 10, (3, 3, 3))
print("Tensor tridimensional:")
print(tensor_tridimensional)

# Calcular la suma de todos los elementos en la dimensión 1.
suma_dim1 = np.sum(tensor_tridimensional, axis=1)
print("\nSuma en la dimensión 1:")
print(suma_dim1)

Tensor tridimensional:
[[[0 1 5]
  [9 3 0]
  [5 8 7]]

 [[6 8 9]
  [6 0 2]
  [2 9 1]]

 [[0 1 3]
  [5 9 5]
  [5 3 0]]]

Suma en la dimensión 1:
[[14 12 12]
 [14 17 12]
 [10 13  8]]
