# Ejercicios Nivel básico

In [2]:
# Importando Librerías
import numpy as np

1. Crea un array de NumPy con los números del 1 al 10.

In [4]:
a =np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Crea dos arrays de NumPy, uno con números pares y otro con números impares del 1 al 10. Realiza una operación de suma entre ambos arrays.

In [10]:
array_pares = np.arange(2,11,2)
array_impares = np.arange(1,11,2)
suma = array_pares + array_impares
print(array_pares)
print(array_impares)
print(suma)

[ 2  4  6  8 10]
[1 3 5 7 9]
[ 3  7 11 15 19]


3. Dado un array de NumPy con números del 1 al 20, imprime los elementos que están en las posiciones impares.

In [15]:
b = np.arange(1,21)
b[1::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

4. Crea una matriz de 3x3 con valores aleatorios. Luego, cambia el valor en la posición (2,2) por 0.

In [22]:
matriz_1 = np.linspace(1,30,9).reshape(3,3)
matriz_2 = np.random.randint(1, 10, (3,3))
print(matriz_2)
matriz_2[2,2]=0
print(matriz_2)

[[8 9 5]
 [9 5 7]
 [8 1 6]]
[[8 9 5]
 [9 5 7]
 [8 1 0]]


5. Crea un array de NumPy con números aleatorios del 1 al 100. Imprime los valores que son mayores que 20 y menor 70

In [26]:
array_3 = np.random.randint(1,101,100)
array_3[(array_3>20) & (array_3<70)]

array([52, 23, 64, 37, 25, 36, 58, 48, 38, 39, 39, 53, 43, 31, 48, 33, 39,
       48, 67, 31, 23, 43, 48, 42, 21, 52, 25, 41, 60, 28, 64, 59, 21, 41,
       31, 49, 41, 36, 28, 59, 50, 67, 25, 45, 61, 26, 24, 38, 57, 36, 59])

# Ejercicios Nivel Intermedio

1. Operaciones Estadísticas:

Genera un array de NumPy con 100 números aleatorios entre 0 y 1. Calcula la media, mediana, desviación estándar y varianza de ese array.

In [33]:
array_4 = np.random.rand(100)
print(f'Media o Promedio: {np.mean(array_4)}')
print(f'Mediana: {np.median(array_4)}')
print(f'Desviación estandar: {np.std(array_4)}')
print(f'Varianza: {np.var(array_4)}')

Media o Promedio: 0.508185742166059
Mediana: 0.5269198914756854
Desviación estandar: 0.3018598047938059
Varianza: 0.09111934175015461


2. Concatenación y Reshape:

Crea dos matrices de 2x3 con números aleatorios. Concaténalas horizontalmente y luego realiza un reshape para convertirla en una matriz de 1x12.

In [43]:
matriz_3 = np.random.randint(0,10,(2,3))
matriz_4 = np.random.randint(0,10,(2,3))
matriz_concatenada = np.concatenate((matriz_3, matriz_4), axis=1).reshape(1, 12)
matriz_concatenada

array([[6, 0, 2, 5, 4, 6, 4, 3, 8, 4, 9, 3]])

3. Operaciones de Álgebra Lineal:

Crea una matriz de 3x3 con números aleatorios y su inversa. Multiplica la matriz original por su inversa y verifica que el resultado sea una matriz de identidad.

In [49]:
matriz_5 = np.random.rand(3,3)
matriz_5_inv = np.linalg.inv(matriz_5)
matriz_identidad = np.dot(matriz_5, matriz_5_inv)
validacion_matriz_identidad = np.allclose(matriz_identidad, np.eye(3))
print(matriz_5 * matriz_5_inv)
print(matriz_identidad)
print(validacion_matriz_identidad)

[[-3.87148858 -0.57215235  0.8987199 ]
 [ 4.3987796   0.05806884 -4.7538983 ]
 [ 3.08195562  1.09298758 -1.02714092]]
[[ 1.00000000e+00 -1.81228626e-17  6.74820082e-17]
 [-5.38673647e-16  1.00000000e+00 -3.33671818e-16]
 [-8.53207282e-16  5.64000872e-17  1.00000000e+00]]
True
