# Ejercicios Nivel Intermedio

In [1]:
# Importando librerias
import numpy as np

1. Operaciones Estadísticas:

Genera un array de NumPy con 100 números aleatorios entre 0 y 1. Calcula la media, mediana, desviación estándar y varianza de ese array.

In [2]:
array_4 = np.random.rand(100)
print(f'Media o Promedio: {np.mean(array_4)}')
print(f'Mediana: {np.median(array_4)}')
print(f'Desviación estandar: {np.std(array_4)}')
print(f'Varianza: {np.var(array_4)}')

Media o Promedio: 0.4449554571329296
Mediana: 0.41126721350194106
Desviación estandar: 0.27629841700223734
Varianza: 0.07634081523794224


2. Concatenación y Reshape:

Crea dos matrices de 2x3 con números aleatorios. Concaténalas horizontalmente y luego realiza un reshape para convertirla en una matriz de 1x12.

In [3]:
matriz_3 = np.random.randint(0,10,(2,3))
matriz_4 = np.random.randint(0,10,(2,3))
matriz_concatenada = np.concatenate((matriz_3, matriz_4), axis=1).reshape(1, 12)
matriz_concatenada

array([[6, 2, 3, 4, 8, 0, 0, 5, 0, 7, 0, 9]])

3. Operaciones de Álgebra Lineal:

Crea una matriz de 3x3 con números aleatorios y su inversa. Multiplica la matriz original por su inversa y verifica que el resultado sea una matriz de identidad.

In [4]:
matriz_5 = np.random.rand(3,3)
matriz_5_inv = np.linalg.inv(matriz_5)
matriz_identidad = np.dot(matriz_5, matriz_5_inv)
validacion_matriz_identidad = np.allclose(matriz_identidad, np.eye(3))
print(matriz_5 * matriz_5_inv)
print(matriz_identidad)
print(validacion_matriz_identidad)

[[ 3.63714577 -3.17735909 -1.80167293]
 [-1.16777793  1.47032181  2.77840741]
 [ 0.09851633  0.71909893 -0.0039782 ]]
[[ 1.00000000e+00  1.46640169e-17 -4.41673641e-17]
 [ 7.49349550e-17  1.00000000e+00 -1.58276230e-16]
 [ 6.45368858e-17  3.26946684e-16  1.00000000e+00]]
True
