# Ejercicios Nivel básico

In [2]:
# Importando Librerías
import numpy as np

1. Crea un array de NumPy con los números del 1 al 10.

In [4]:
a =np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Crea dos arrays de NumPy, uno con números pares y otro con números impares del 1 al 10. Realiza una operación de suma entre ambos arrays.

In [10]:
array_pares = np.arange(2,11,2)
array_impares = np.arange(1,11,2)
suma = array_pares + array_impares
print(array_pares)
print(array_impares)
print(suma)

[ 2  4  6  8 10]
[1 3 5 7 9]
[ 3  7 11 15 19]


3. Dado un array de NumPy con números del 1 al 20, imprime los elementos que están en las posiciones impares.

In [15]:
b = np.arange(1,21)
b[1::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

4. Crea una matriz de 3x3 con valores aleatorios. Luego, cambia el valor en la posición (2,2) por 0.

In [22]:
matriz_1 = np.linspace(1,30,9).reshape(3,3)
matriz_2 = np.random.randint(1, 10, (3,3))
print(matriz_2)
matriz_2[2,2]=0
print(matriz_2)

[[8 9 5]
 [9 5 7]
 [8 1 6]]
[[8 9 5]
 [9 5 7]
 [8 1 0]]


5. Crea un array de NumPy con números aleatorios del 1 al 100. Imprime los valores que son mayores que 20 y menor 70

In [26]:
array_3 = np.random.randint(1,101,100)
array_3[(array_3>20) & (array_3<70)]

array([52, 23, 64, 37, 25, 36, 58, 48, 38, 39, 39, 53, 43, 31, 48, 33, 39,
       48, 67, 31, 23, 43, 48, 42, 21, 52, 25, 41, 60, 28, 64, 59, 21, 41,
       31, 49, 41, 36, 28, 59, 50, 67, 25, 45, 61, 26, 24, 38, 57, 36, 59])